/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Satellite struct for Satellite
type Satellite struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Region string `json:"region,omitempty"`
	Network string `json:"network,omitempty"`
	Pools []Pool `json:"pools,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	Actived bool `json:"actived,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
