/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Invitation struct {
	Id        string               `json:"id,omitempty"`
	InvitedBy *InvitationInvitedBy `json:"invited_by,omitempty"`
	Team      *InvitationTeam      `json:"team,omitempty"`
	User      *InvitationUser      `json:"user,omitempty"`
	CreatedAt string               `json:"created_at,omitempty"`
	UpdatedAt string               `json:"updated_at,omitempty"`
}
