/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PoolLaunchSpecification struct for PoolLaunchSpecification
type PoolLaunchSpecification struct {
	Config map[string]PoolLaunchSpecificationConfig `json:"config,omitempty"`
	RootDisk PoolLaunchSpecificationRootDisk `json:"root_disk,omitempty"`
}
