/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Event struct {
	Id        string `json:"id,omitempty"`
	UserId    string `json:"user_id,omitempty"`
	Service   string `json:"service,omitempty"`
	Path      string `json:"path,omitempty"`
	Method    string `json:"method,omitempty"`
	Code      int32  `json:"code,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
