/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Event struct for Event
type Event struct {
	Id string `json:"id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	Service string `json:"service,omitempty"`
	Path string `json:"path,omitempty"`
	Method string `json:"method,omitempty"`
	Code int32 `json:"code,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
