/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Satellite struct {
	Id          string            `json:"id,omitempty"`
	Name        string            `json:"name,omitempty"`
	Description string            `json:"description,omitempty"`
	Region      string            `json:"region,omitempty"`
	Network     string            `json:"network,omitempty"`
	Pools       []Pool            `json:"pools,omitempty"`
	Tags        map[string]string `json:"tags,omitempty"`
	Actived     bool              `json:"actived,omitempty"`
	CreatedAt   string            `json:"created_at,omitempty"`
	UpdatedAt   string            `json:"updated_at,omitempty"`
}
