/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountDefaultTeam struct for AccountDefaultTeam
type AccountDefaultTeam struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
