/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type PoolAutoscaling struct {
	Engine              []string `json:"engine,omitempty"`
	PreemptiblePourcent float32  `json:"preemptible_pourcent,omitempty"`
	MaxCpu              int32    `json:"max_cpu,omitempty"`
	MaxMemory           int32    `json:"max_memory,omitempty"`
}
