/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Account struct {
	Id                      string              `json:"id,omitempty"`
	Firstname               string              `json:"firstname,omitempty"`
	Lastname                string              `json:"lastname,omitempty"`
	Email                   string              `json:"email,omitempty"`
	TwoFactorAuthentication bool                `json:"two_factor_authentication,omitempty"`
	Verified                bool                `json:"verified,omitempty"`
	DefaultTeam             *AccountDefaultTeam `json:"default_team,omitempty"`
	LastLogin               string              `json:"last_login,omitempty"`
	CreatedAt               string              `json:"created_at,omitempty"`
	UpdatedAt               string              `json:"updated_at,omitempty"`
}
