/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Invoice struct {
	Id           string  `json:"id,omitempty"`
	ChargesTotal float32 `json:"charges_total,omitempty"`
	CreditsTotal float32 `json:"credits_total,omitempty"`
	Total        float32 `json:"total,omitempty"`
	PeriodStart  string  `json:"period_start,omitempty"`
	PeriodEnd    string  `json:"period_end,omitempty"`
	Payed        bool    `json:"payed,omitempty"`
	CreatedAt    string  `json:"created_at,omitempty"`
	UpdatedAt    string  `json:"updated_at,omitempty"`
}
