/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PoolLaunchSpecificationRootDisk struct for PoolLaunchSpecificationRootDisk
type PoolLaunchSpecificationRootDisk struct {
	Ami string `json:"ami,omitempty"`
	Size int32 `json:"size,omitempty"`
	Type string `json:"type,omitempty"`
}
