/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PoolAutoscaling struct for PoolAutoscaling
type PoolAutoscaling struct {
	Engine []string `json:"engine,omitempty"`
	PreemptiblePourcent float32 `json:"preemptible_pourcent,omitempty"`
	MinInstances float32 `json:"min_instances,omitempty"`
	MaxCpu int32 `json:"max_cpu,omitempty"`
	MaxMemory int32 `json:"max_memory,omitempty"`
}
