/*
 * Universe.sh houston API
 *
 * Universe.sh houston API
 *
 * API version: 1.0.0
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Preferences struct for Preferences
type Preferences struct {
	DefaultPermission string `json:"default-permission,omitempty"`
}
