/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Metric struct {
	Id        string       `json:"id,omitempty"`
	Name      string       `json:"name,omitempty"`
	Type_     string       `json:"type,omitempty"`
	Data      []MetricData `json:"data,omitempty"`
	CreatedAt string       `json:"created_at,omitempty"`
}
