/*
 * Universe.sh API houston
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: developper@universe.sh
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type PoolLaunchSpecificationConfig struct {
	Subnetwork string `json:"subnetwork,omitempty"`
	Template   string `json:"template,omitempty"`
}
